apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcs-simulator.fullname" . }}
  labels:
    {{- include "gcs-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gcs-simulator.selectorLabels" . | nindent 4 }}
